version: "3.9"

services:
    web:
        ports:
            - 3000:3000
        networks:
            - webnet
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - node_modules:/app/node_modules
            - ./:/app
networks:
    webnet:
volumes:
    node_modules:
